### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by pavarnos** [cadrephp/Cadre.Dispatcher#1]
Hi. Just stumbled across your project while looking at other Aura related stuff. (Looking good!) I'm currently using Symfony for DI and event dispatch, but not so deeply it will be hard to change... I found that I had several hundred listeners to register and wanted to do that at release time rather than on every request. Here is how I solved it. Might be some ideas you could steal / borrow?

https://medium.com/@pavarnos/lazy-event-dispatching-with-symfony-1fc8813c44e1#.r1nxaytfb

Hope this helps. 
Feel free to close this Issue: couldn't see any other way to send you this...

**Comment by andrewshell** [comment]
Thanks for the link. I'm debating if I'm going to continue with this project as I just came across [Tactician](http://tactician.thephpleague.com/) which allows me to do what I'm doing with this and much more.  The only think it misses is the ability to register multiple listeners for a single event, but I think I can get around that with middleware.
